import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import Project from './components/Project'
// import axios from 'axios'

export default function Home() {
  const [weatherData, setWeatherData] = useState({});
  const [selectedCity, setSelectedCity] = useState("Sanaa");
  // const [loading, setLoading] = useState(false)

 
  const handleClick = (name) => {
    setSelectedCity(name);
  };
const [weather, setWeather] = useState();

  useEffect(() => {
   
    fetch(
      `https://api.openweathermap.org/data/2.5/weather?q=${selectedCity}&units=imperial&appid=52922fa07c551a030f9701eff376927a`
    )
      .then((res) => res.json())
      .then((res) => {
        setWeatherData(res);
        console.log(res)
        console.log(weatherData)
      })
      .catch((err) => console.error(err));
   }, [selectedCity]);
    if ( !weatherData) {
      return <div>Loading...</div>;
    }

return (
  < div>
     <Head>
       <title>Create Next App</title>
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/favicon.ico" />
     </Head>
    <main><Project OnClick={handleClick} weather={weatherData} /></main> 
     {/* <search/> */}

   </div>
 )}
